const routes=[['home','الرئيسية'],['command','مركز الأوامر'],['employees','الموظفون'],['projects','المشاريع'],['tasks','المهام'],['approvals','الموافقات'],['connections','الاتصالات'],['reports','التقارير'],['finance','المالية'],['activity','النشاط'],['health','الإعدادات']];
const state={route:'home',data:null,health:null,token:sessionStorage.getItem('hq_v2_token')||''};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fallbackNames={sara:'سارة',omar:'عمر',fahad:'فهد',lian:'ليان',noura:'نورة',rakan:'راكان'};
const employeeName=id=>state.data?.employees?.find(e=>e.id===id)?.name_ar||fallbackNames[id]||id||'—';
const statusLabel={READY:'جاهز',WORKING:'يعمل',RESEARCHING:'يبحث',REVIEWING:'يراجع',WAITING:'بانتظار',ERROR:'خطأ',QUEUED:'بالطابور',ROUTING:'توجيه',PLANNING:'تخطيط',WAITING_FOR_CONNECTION:'بانتظار ربط',WAITING_FOR_APPROVAL:'بانتظار موافقة',PAUSED_EXTERNAL:'تعليق خارجي',BLOCKED:'متوقفة',COMPLETED:'مكتملة',FAILED:'فشلت',CANCELLED:'ملغاة',ACTIVE:'نشط',PLANNED:'مخطط'};
const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${state.token}`,...options.headers}});const d=await r.json();if(r.status===401||r.status===503&&d.error==='HQ_V2_ACCESS_TOKEN_NOT_CONFIGURED')throw Object.assign(new Error(d.error),{auth:true});if(!r.ok)throw Object.assign(new Error(d.error||'REQUEST_FAILED'),{status:r.status,data:d});return d;};
function nav(){const desktop=$('#nav'),mobile=$('#bottomNav');desktop.innerHTML=routes.map(([id,label])=>`<button class="nav-btn ${state.route===id?'active':''}" data-route="${id}">${label}</button>`).join('');mobile.innerHTML=routes.slice(0,5).map(([id,label])=>`<button class="nav-btn ${state.route===id?'active':''}" data-route="${id}">${label}</button>`).join('');}
function status(value){return `<span class="status ${String(value).toLowerCase()}">${statusLabel[value]||esc(value)}</span>`;}
function employeeCard(e){return `<article class="employee" data-employee="${e.id}" tabindex="0"><div class="employee-top"><span class="avatar">${esc(e.name_ar[0])}</span><div><h3>${esc(e.name_ar)}</h3><small>${esc(e.role)}</small></div></div>${status(e.status)}${e.current_task_id?`<small>مهمة نشطة</small>`:''}</article>`;}
function taskRow(t){return `<article class="task" data-task="${t.id}" tabindex="0"><div><h3>${esc(t.title)}</h3><span class="task-meta">${esc(employeeName(t.employee_id))} · ${esc(t.project_id||'الشركة')} · ${new Date(t.created_at).toLocaleString('ar-SA')}</span></div>${status(t.status)}</article>`;}
function commandHero(){return `<section class="hero"><p class="eyebrow">Company Copilot</p><h2>وش تبغى الشركة تسوي؟</h2><p>اكتب بطريقتك. النظام يحدد الموظف والمشروع والأداة تلقائيًا، وإذا ذكرت موظف باسمه الحالي يحترم اختيارك.</p><form class="command-box" id="commandForm"><textarea id="commandInput" aria-label="أمر الشركة" placeholder="مثال: فهد فكر لي بفكرة موقع جديدة"></textarea><button type="button" class="icon-btn" id="voiceBtn" aria-label="إملاء صوتي">◉</button><button class="primary">تنفيذ</button></form><div class="suggestions"><button class="chip">سارة وش وضع الشركة؟</button><button class="chip">نورة راجعي مشروع معين</button><button class="chip">راكان حلل أرامكو</button><button class="chip">فهد فكر لي بفكرة موقع جديدة</button></div></section>`;}
function home(){const d=state.data,active=d.tasks.filter(t=>['WORKING','RESEARCHING','REVIEWING','ROUTING','PLANNING'].includes(t.status)),completed=d.tasks.filter(t=>t.status==='COMPLETED');return `${commandHero()}<section class="metrics"><article class="metric"><span>يعملون الآن</span><strong>${d.employees.filter(e=>!['READY','OFFLINE'].includes(e.status)).length}</strong></article><article class="metric"><span>مهام نشطة</span><strong>${active.length}</strong></article><article class="metric"><span>تحتاج موافقة</span><strong>${d.approvals.length}</strong></article><article class="metric"><span>اكتملت</span><strong>${completed.length}</strong></article></section><section class="grid-2"><article class="section-card"><div class="section-head"><h2>الفريق الآن</h2><button class="text-btn" data-route="employees">عرض الكل</button></div><div class="employee-grid">${d.employees.map(employeeCard).join('')}</div></article><article class="section-card"><div class="section-head"><h2>آخر النتائج</h2><button class="text-btn" data-route="tasks">كل المهام</button></div><div class="task-list">${completed.slice(0,5).map(taskRow).join('')||'<p class="empty">لا توجد نتائج مكتملة بعد.</p>'}</div></article></section>`;}
function command(){return `${commandHero()}<div class="bottom-space"></div><article class="section-card"><div class="section-head"><h2>سجل الأوامر</h2><span class="task-meta">اضغط أي أمر للنقاش أو الحذف أو إنشاء متابعة</span></div><div class="task-list">${state.data.tasks.slice(0,20).map(taskRow).join('')||'<p class="empty">لا توجد أوامر.</p>'}</div></article>`;}
function employees(){return `<div class="view-title"><div><p class="eyebrow">القوة العاملة</p><h2>الموظفون</h2><p>اضغط الموظف لتعديل الاسم والمنصب والتعليمات الخاصة.</p></div></div><div class="project-grid">${state.data.employees.map(e=>`<article class="project" data-employee="${e.id}" tabindex="0"><div class="employee-top"><span class="avatar">${esc(e.name_ar[0])}</span><div><h3>${esc(e.name_ar)}</h3><p>${esc(e.role)}</p></div></div>${status(e.status)}<p>${esc(e.department)} · الأدوات: ${(e.preferred_tools||[]).map(esc).join('، ')||'حسب المهمة'}</p>${e.custom_instructions?`<small>تعليمات خاصة محفوظة</small>`:''}</article>`).join('')}</div>`;}
function projects(){return `<div class="view-title"><div><p class="eyebrow">المحفظة</p><h2>المشاريع</h2></div></div><div class="project-grid">${state.data.projects.map(p=>`<article class="project"><span class="eyebrow">${statusLabel[p.status]||p.status}</span><h3>${esc(p.name_ar)}</h3><p>${esc(p.name_en)} · ${esc((p.owners||[]).map(employeeName).join('، '))}</p><div class="project-actions">${p.live_url?`<a class="link-btn" href="${esc(p.live_url)}" target="_blank" rel="noreferrer">فتح الموقع</a>`:''}${p.repository_url?`<a class="link-btn" href="${esc(p.repository_url)}" target="_blank" rel="noreferrer">المستودع</a>`:''}</div></article>`).join('')}</div>`;}
function tasks(){return `<div class="view-title"><div><p class="eyebrow">التنفيذ الحقيقي</p><h2>المهام</h2><p>افتح أي مهمة عشان تناقش الموظف أو تكمل منها أو تحذفها من السجل.</p></div></div><div class="table-wrap"><table><thead><tr><th>المهمة</th><th>الموظف</th><th>المشروع</th><th>المسار</th><th>الحالة</th><th>آخر تحديث</th></tr></thead><tbody>${state.data.tasks.map(t=>`<tr data-task="${t.id}" tabindex="0"><td>${esc(t.title)}</td><td>${esc(employeeName(t.employee_id))}</td><td>${esc(t.project_id||'الشركة')}</td><td>${esc(t.route)}</td><td>${status(t.status)}</td><td>${new Date(t.updated_at).toLocaleString('ar-SA')}</td></tr>`).join('')}</tbody></table></div>`;}
function approvals(){return listCards('الموافقات','قرارات عالية التأثير',state.data.approvals,a=>`<article class="section-card"><h3>${esc(a.action)}</h3><p>${esc(a.reason)} · التأثير: ${esc(a.impact)}</p><div class="project-actions"><button class="primary" data-approval="${a.id}" data-decision="approve">موافقة</button><button class="link-btn" data-approval="${a.id}" data-decision="reject">رفض</button></div></article>`);}
function connections(){return listCards('الاتصالات','الأدوات المطلوبة',state.data.connections,c=>`<article class="section-card"><p class="eyebrow">${esc(c.provider)}</p><h3>${esc(c.reason)}</h3><p>الصلاحيات: ${(c.permissions||[]).map(esc).join('، ')} · تكلفة: ${c.costs_money?'قد توجد':'لا'}</p><div class="project-actions"><button class="primary" data-connection="${c.id}" data-decision="approve">ربط/إعادة فحص</button><button class="link-btn" data-connection="${c.id}" data-decision="reject">رفض</button></div></article>`);}
function reports(){return listCards('التقارير','نتائج موثقة',state.data.tasks.filter(t=>t.result),t=>`<article class="section-card" data-task="${t.id}"><p class="eyebrow">${esc(t.route)}</p><h3>${esc(t.title)}</h3><p>${esc(t.result?.summary||'')}</p></article>`);}
function finance(){const f=state.data.finance||{},cash=Number(f.account?.cash||0);return `<div class="view-title"><div><p class="eyebrow">PAPER / SIMULATED</p><h2>مركز راكان المالي</h2></div></div><section class="metrics"><article class="metric"><span>النقد التجريبي</span><strong>$${cash.toLocaleString()}</strong></article><article class="metric"><span>المراكز</span><strong>${f.positions?.length||0}</strong></article><article class="metric"><span>الأوامر</span><strong>${f.orders?.length||0}</strong></article><article class="metric"><span>أموال حقيقية</span><strong>$0</strong></article></section><article class="section-card"><div class="section-head"><h2>المراكز التجريبية</h2></div><div class="task-list">${(f.positions||[]).map(p=>`<div class="task"><div><h3>${esc(p.symbol)}</h3><span class="task-meta">الكمية ${Number(p.quantity).toFixed(4)} · متوسط ${Number(p.average_cost).toFixed(2)}</span></div><span class="eyebrow">PAPER</span></div>`).join('')||'<p class="empty">لا توجد مراكز تجريبية.</p>'}</div></article>`;}
function activity(){return listCards('النشاط','أحداث حقيقية فقط',state.data.activity,a=>`<article class="item"><strong>${esc(a.message)}</strong><p>${new Date(a.created_at).toLocaleString('ar-SA')}</p></article>`);}
function healthView(){const checks=state.health?.checks||{};return `<div class="view-title"><div><p class="eyebrow">قياس مباشر</p><h2>صحة النظام</h2></div></div><div class="project-grid">${Object.entries(checks).map(([name,x])=>`<article class="project"><h3>${esc(name)}</h3>${status(x.status)}<p>${esc(x.detail||'آخر فحص: الآن')}</p></article>`).join('')}</div>`;}
function listCards(title,sub,items,render){return `<div class="view-title"><div><p class="eyebrow">${esc(sub)}</p><h2>${esc(title)}</h2></div></div><div class="task-list">${items.map(render).join('')||'<article class="section-card empty">لا توجد عناصر حاليًا.</article>'}</div>`;}
const renderers={home,command,employees,projects,tasks,approvals,connections,reports,finance,activity,health:healthView};
function render(){nav();$('#pageTitle').textContent=routes.find(x=>x[0]===state.route)?.[1]||'NAWAF HQ';$('#view').innerHTML=state.data?renderers[state.route]():'<div class="empty">جاري تحميل بيانات الشركة…</div>';wire();renderRail();ensureEmployeeDialog();}
function renderRail(){if(!state.data)return;$('#briefs').innerHTML=state.data.briefs.slice(0,3).map(b=>`<article class="item"><strong>${esc(b.title)}</strong><p>${esc(b.body)}</p></article>`).join('')||'لا توجد ملخصات بعد.';const att=[...state.data.approvals,...state.data.connections];$('#attentionCount').textContent=att.length;$('#attention').innerHTML=att.slice(0,4).map(x=>`<article class="item"><strong>${esc(x.action||x.provider)}</strong><p>${esc(x.reason)}</p></article>`).join('')||'لا توجد طلبات معلّقة.';const checks=state.health?.checks||{};$('#healthMini').innerHTML=Object.entries(checks).slice(0,5).map(([n,x])=>`<div class="health-row"><span>${esc(n)}</span>${status(x.status)}</div>`).join('');}
function wire(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route));document.querySelectorAll('[data-task]').forEach(el=>el.onclick=()=>openTask(el.dataset.task));document.querySelectorAll('[data-employee]').forEach(el=>el.onclick=()=>openEmployee(el.dataset.employee));document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$('#commandInput').value=b.textContent;});const form=$('#commandForm');if(form)form.onsubmit=submitCommand;const voice=$('#voiceBtn');if(voice)voice.onclick=startVoice;document.querySelectorAll('[data-approval]').forEach(b=>b.onclick=()=>decide(b.dataset.approval,b.dataset.decision));document.querySelectorAll('[data-connection]').forEach(b=>b.onclick=()=>decideConnection(b.dataset.connection,b.dataset.decision));}
function go(route){state.route=route;history.replaceState({},'',`#${route}`);render();}
async function load(){try{const [snap,h]=await Promise.all([api('/api/v2/snapshot'),fetch('/api/v2/health').then(r=>r.json())]);state.data=snap.data;state.health=h;const bad=Object.values(h.checks||{}).some(x=>x.status==='Unavailable');$('#healthDot').className=`health-dot ${bad?'bad':'good'}`;$('#healthLabel').textContent=bad?'تحتاج انتباه':'الأنظمة مستقرة';render();}catch(error){if(error.auth){$('#authDialog').showModal();return;}$('#view').innerHTML=`<article class="section-card"><h2>تعذر تحميل الحالة</h2><p>${esc(error.message)}</p></article>`;}}
async function submitCommand(e){e.preventDefault();const input=$('#commandInput'),command=input.value.trim();if(!command)return;const btn=e.submitter;btn.disabled=true;btn.textContent='جاري التوجيه…';try{await api('/api/v2/tasks',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({command})});input.value='';await load();}catch(error){alert(`تعذر تنفيذ الأمر: ${error.message}`);}finally{btn.disabled=false;btn.textContent='تنفيذ';}}
function discussionHtml(messages,employeeId){return messages?.length?messages.map(m=>`<div class="item"><strong>${m.author_type==='owner'?'نواف':m.author_type==='system'?'النظام':esc(employeeName(m.employee_id||employeeId))}</strong><p>${esc(m.content)}</p><small>${new Date(m.created_at).toLocaleString('ar-SA')}</small></div>`).join(''):'<p class="empty">ما بدأ النقاش على هالمهمة بعد.</p>';}
async function openTask(id){try{const d=await api(`/api/v2/tasks/${id}`);$('#taskDialogTitle').textContent=d.task.title;$('#taskDialogBody').innerHTML=`<div class="metrics"><article class="metric"><span>الموظف</span><strong>${esc(employeeName(d.task.employee_id))}</strong></article><article class="metric"><span>الحالة</span><strong>${esc(statusLabel[d.task.status]||d.task.status)}</strong></article></div><h3>النتيجة</h3><p>${esc(d.task.result?.summary||d.task.error_message||'لم تظهر نتيجة نهائية بعد.')}</p><h3>ناقش ${esc(employeeName(d.task.employee_id))}</h3><div class="task-list" id="discussionList">${discussionHtml(d.messages,d.task.employee_id)}</div><form id="discussionForm" class="command-box"><textarea id="discussionInput" placeholder="ناقش الفكرة، عدّلها، اسأل الموظف…"></textarea><button class="primary">إرسال</button></form><div class="project-actions"><button class="primary" id="continueTaskBtn">نفّذ المتفق عليه</button><button class="link-btn" id="archiveTaskBtn">حذف الأمر</button></div><h3>خط التنفيذ</h3><div class="timeline">${d.events.map(x=>`<div class="timeline-item"><strong>${esc(statusLabel[x.stage]||x.message)}</strong><small>${new Date(x.created_at).toLocaleString('ar-SA')}</small></div>`).join('')}</div><h3>الأدلة</h3><div class="evidence">${d.evidence.map(x=>`<div class="item"><strong>${esc(x.label)}</strong>${x.uri?`<p><a href="${esc(x.uri)}" target="_blank" rel="noreferrer">فتح الدليل</a></p>`:''}</div>`).join('')||'<p class="empty">لا توجد أدلة بعد.</p>'}</div>`;$('#taskDialog').showModal();$('#discussionForm').onsubmit=e=>sendDiscussion(e,id,d.task.employee_id);$('#continueTaskBtn').onclick=()=>continueTask(id);$('#archiveTaskBtn').onclick=()=>archiveTask(id);}catch(error){alert(error.message);}}
async function sendDiscussion(e,id,employeeId){e.preventDefault();const input=$('#discussionInput'),content=input.value.trim();if(!content)return;const btn=e.submitter;btn.disabled=true;btn.textContent='يفكر…';try{await api(`/api/v2/tasks/${id}/discussion`,{method:'POST',body:JSON.stringify({content})});input.value='';const d=await api(`/api/v2/tasks/${id}/discussion`);$('#discussionList').innerHTML=discussionHtml(d.messages,employeeId);$('#discussionList').lastElementChild?.scrollIntoView({behavior:'smooth'});}catch(error){alert(`تعذر النقاش: ${error.message}`);}finally{btn.disabled=false;btn.textContent='إرسال';}}
async function continueTask(id){const instruction=prompt('وش تبيهم ينفذون من النقاش؟','نفّذ النسخة المتفق عليها في النقاش.');if(instruction===null)return;try{const d=await api(`/api/v2/tasks/${id}/continue`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({instruction})});$('#taskDialog').close();await load();setTimeout(()=>openTask(d.task.id),800);}catch(error){alert(`تعذر إنشاء مهمة المتابعة: ${error.message}`);}}
async function archiveTask(id){if(!confirm('تحذف هذا الأمر من السجل الظاهر؟ البيانات تبقى محفوظة داخليًا للتدقيق.'))return;try{await api(`/api/v2/tasks/${id}/archive`,{method:'POST',body:'{}'});$('#taskDialog').close();await load();}catch(error){alert(error.message==='TASK_ACTIVE_CANNOT_ARCHIVE'?'المهمة تعمل الآن. انتظر حتى تنتهي ثم احذفها.':`تعذر الحذف: ${error.message}`);}}
function ensureEmployeeDialog(){if($('#employeeEditDialog'))return;const dialog=document.createElement('dialog');dialog.id='employeeEditDialog';dialog.innerHTML=`<form id="employeeEditForm" class="auth-card"><div class="section-head"><h2 id="employeeEditTitle">تعديل الموظف</h2><button type="button" class="icon-btn" id="employeeEditClose">×</button></div><input type="hidden" id="employeeEditId"><label>الاسم<input id="employeeNameAr" maxlength="80" required></label><label>المنصب<select id="employeeRoleSelect"></select></label><label id="customRoleWrap" class="hidden">منصب جديد<input id="employeeCustomRole" maxlength="120" placeholder="مثال: مدير ابتكار"></label><label>القسم<input id="employeeDepartment" maxlength="120"></label><label>تعليمات خاصة<textarea id="employeeInstructions" maxlength="4000" placeholder="مثال: لا تعطيني ردود عامة، اقترح 3 خيارات ثم اختر الأقوى"></textarea></label><label>الصلاحيات — افصل بفاصلة<input id="employeePermissions" placeholder="research, qa"></label><div class="project-actions"><button class="primary">حفظ</button></div></form>`;document.body.append(dialog);$('#employeeEditClose').onclick=()=>dialog.close();$('#employeeRoleSelect').onchange=()=>$('#customRoleWrap').classList.toggle('hidden',$('#employeeRoleSelect').value!=='__custom__');$('#employeeEditForm').onsubmit=saveEmployee;}
function openEmployee(id){ensureEmployeeDialog();const e=state.data.employees.find(x=>x.id===id);if(!e)return;const roles=state.data.roles||[];$('#employeeEditId').value=e.id;$('#employeeEditTitle').textContent=`تعديل ${e.name_ar}`;$('#employeeNameAr').value=e.name_ar;$('#employeeDepartment').value=e.department||'';$('#employeeInstructions').value=e.custom_instructions||'';$('#employeePermissions').value=(e.permissions||[]).join(', ');const hasRole=roles.some(r=>r.name===e.role);$('#employeeRoleSelect').innerHTML=`${roles.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}${r.is_preset?'':' · مخصص'}</option>`).join('')}<option value="__custom__">+ أضف منصب من عندي</option>`;$('#employeeRoleSelect').value=hasRole?e.role:'__custom__';$('#employeeCustomRole').value=hasRole?'':e.role;$('#customRoleWrap').classList.toggle('hidden',hasRole);$('#employeeEditDialog').showModal();}
async function saveEmployee(e){e.preventDefault();const id=$('#employeeEditId').value,name_ar=$('#employeeNameAr').value.trim(),roleValue=$('#employeeRoleSelect').value,customRole=$('#employeeCustomRole').value.trim(),department=$('#employeeDepartment').value.trim()||'عام',custom_instructions=$('#employeeInstructions').value.trim(),permissions=$('#employeePermissions').value.split(',').map(x=>x.trim()).filter(Boolean);let role=roleValue,role_source='preset';const btn=e.submitter;btn.disabled=true;btn.textContent='جاري الحفظ…';try{if(roleValue==='__custom__'){if(!customRole)throw new Error('اكتب اسم المنصب الجديد');role=customRole;role_source='custom';try{await api('/api/v2/roles',{method:'POST',body:JSON.stringify({name:role,department,description:'منصب مخصص أنشأه نواف',capabilities:permissions})});}catch(error){if(error.message!=='ROLE_ALREADY_EXISTS')throw error;}}await api(`/api/v2/employees/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({name_ar,role,role_source,department,custom_instructions,permissions})});$('#employeeEditDialog').close();await load();}catch(error){alert(`تعذر الحفظ: ${error.message}`);}finally{btn.disabled=false;btn.textContent='حفظ';}}
async function decide(id,decision){await api(`/api/v2/approvals/${id}/${decision}`,{method:'POST',body:'{}'});await load();}
async function decideConnection(id,decision){const d=await api(`/api/v2/connections/${id}/${decision}`,{method:'POST',body:'{}'});if(d.message)alert(d.message);await load();}
function startVoice(){const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SpeechRecognition)return alert('الإملاء الصوتي غير مدعوم في هذا المتصفح.');const r=new SpeechRecognition();r.lang='ar-SA';r.interimResults=false;r.onresult=e=>{$('#commandInput').value=e.results[0][0].transcript;};r.start();}
$('#authForm').addEventListener('submit',e=>{e.preventDefault();state.token=$('#tokenInput').value.trim();sessionStorage.setItem('hq_v2_token',state.token);$('#authDialog').close();load();});
document.addEventListener('click',e=>{const route=e.target.closest('[data-route]')?.dataset.route;if(route)go(route);});
state.route=location.hash.slice(1)||'home';nav();load();const events=new EventSource('/api/v2/events');events.addEventListener('state.changed',()=>load());events.addEventListener('task.created',()=>load());events.addEventListener('task.discussion',()=>{});setInterval(load,60000);
