const state={token:sessionStorage.getItem('hq_v2_token')||'',context:null,speak:localStorage.getItem('nav_speak')!=='off'};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const terminal=new Set(['COMPLETED','FAILED','BLOCKED','CANCELLED','WAITING_FOR_CONNECTION','WAITING_FOR_APPROVAL']);
const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${state.token}`,...options.headers}});const d=await r.json();if(r.status===401||r.status===503&&d.error==='HQ_V2_ACCESS_TOKEN_NOT_CONFIGURED')throw Object.assign(new Error(d.error),{auth:true});if(!r.ok)throw Object.assign(new Error(d.error||'REQUEST_FAILED'),{data:d,status:r.status});return d;};
function speak(text){if(!state.speak||!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text).slice(0,900));u.lang='ar-SA';u.rate=1.08;window.speechSynthesis.speak(u)}
function msg(role,content,meta=''){const box=$('#messages');const el=document.createElement('article');el.className=`msg ${role}`;el.innerHTML=`${esc(content)}${meta?`<span class="meta">${esc(meta)}</span>`:''}`;box.append(el);box.scrollTop=box.scrollHeight;return el}
function renderMessages(items){const box=$('#messages');box.innerHTML='';if(!items?.length)msg('assistant','هلا نواف. أنا ناڤ. أقدر أساعدك شخصيًا، وإذا عطيتني أمر للشركة أحوله لنفس محرك NAWAF HQ الحقيقي.');else items.slice(-30).forEach(x=>msg(x.role==='user'?'user':'assistant',x.content,x.mode==='company'?'من محرك الشركة':''));}
function renderMemories(items){$('#memories').innerHTML=items?.length?items.map(x=>`<article class="memory"><p>${esc(x.content)}</p><footer><span>أهمية ${x.importance}/5</span><button class="text-btn" data-archive="${x.id}">إخفاء</button></footer></article>`).join(''):'<p class="meta">ما فيه ذاكرة محفوظة داخل تطبيق ناڤ بعد.</p>';document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archiveMemory(b.dataset.archive));}
function renderCompany(c){$('#companyState').innerHTML=`<div class="stat"><strong>${Number(c?.activeTasks||0)}</strong><span>مهام نشطة</span></div><div class="stat"><strong>${Number(c?.attention||0)}</strong><span>تحتاج انتباه</span></div><div class="stat"><strong>${c?.employees?.filter(e=>!['READY','OFFLINE'].includes(e.status)).length||0}</strong><span>يعملون الآن</span></div><div class="stat"><strong>${c?.projects?.filter(p=>p.status==='ACTIVE').length||0}</strong><span>مشاريع نشطة</span></div>`;}
function renderCapabilities(ctx){const backend=(ctx.serverAdapters||[]).map(a=>`<article class="cap"><p><strong>${esc(a.provider)}</strong></p><footer><span>${esc((a.capabilities||[]).join(' · '))}</span><span>داخل HQ</span></footer></article>`).join('');const connectors=(ctx.chatgptConnectors||[]).map(a=>`<article class="cap"><p><strong>${esc(a.name)}</strong></p><footer><span>${esc((a.capabilities||[]).join(' · '))}</span><span>ChatGPT فقط</span></footer></article>`).join('');$('#capabilities').innerHTML=backend+connectors;}
async function load(){try{const d=await api('/api/v2/nav/context');state.context=d.data;$('#status').textContent='متصل';$('#status').className='status good';renderMessages(d.data.messages);renderMemories(d.data.memories);renderCompany(d.data.company);renderCapabilities(d.data);wireStream();}catch(error){if(error.auth)return askAuth();$('#status').textContent='تعذر الاتصال';$('#status').className='status bad';msg('assistant','تعذر تحميل ناڤ الآن. جرّب تحديث الصفحة.');}}
function askAuth(){const dlg=$('#authDialog');if(!dlg.open)dlg.showModal();}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();state.token=$('#tokenInput').value.trim();sessionStorage.setItem('hq_v2_token',state.token);$('#authDialog').close();await load();});
$('#speakToggle').textContent=state.speak?'🔊':'🔇';$('#speakToggle').onclick=()=>{state.speak=!state.speak;localStorage.setItem('nav_speak',state.speak?'on':'off');$('#speakToggle').textContent=state.speak?'🔊':'🔇';if(!state.speak&&'speechSynthesis'in window)window.speechSynthesis.cancel();};
async function sendMessage(text){const message=String(text||'').trim();if(!message)return;$('#handoff').classList.add('hidden');msg('user',message);$('#messageInput').value='';const pending=msg('assistant','قاعد أنفذ/أفكر…');try{const d=await api('/api/v2/nav/chat',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({message})});pending.remove();if(d.kind==='company_task'){msg('assistant',`تم تحويله لمحرك الشركة. ${d.task.title}`,'تنفيذ حقيقي · جاري المتابعة');await pollTask(d.task.id);return;}if(d.kind==='chatgpt_handoff'){msg('assistant',d.text,`يتطلب ${d.provider} داخل ChatGPT`);const h=$('#handoff');h.textContent=`موصل ${d.provider} مربوط بحساب ChatGPT، لكنه مو OAuth داخل تطبيق ناڤ نفسه. نفس الطلب محفوظ وتقدر تنفذه من محادثة ChatGPT.`;h.classList.remove('hidden');return;}msg('assistant',d.text);speak(d.text);}catch(error){pending.remove();msg('assistant',error.auth?'انتهت جلسة الدخول. أدخل المفتاح من جديد.':'صار خطأ فعلي أثناء التنفيذ وما راح أدّعي نجاحه.');if(error.auth)askAuth();}}
async function pollTask(id){const started=Date.now();let last='';while(Date.now()-started<360000){await new Promise(r=>setTimeout(r,2500));try{const d=await api(`/api/v2/tasks/${id}`),t=d.task;if(t.status!==last){last=t.status;msg('assistant',`حالة المهمة: ${t.status}`,'متابعة مباشرة');}if(terminal.has(t.status)){if(t.result?.summary){msg('assistant',t.result.summary,`النتيجة: ${t.status}`);speak(t.result.summary)}else if(t.error_message)msg('assistant',t.error_message,`النتيجة: ${t.status}`);await refreshContext(false);return;}}catch{return}}msg('assistant','المهمة ما زالت مستمرة بالخلفية. تقدر تتابعها من NAWAF HQ.');}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();sendMessage($('#messageInput').value)});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>sendMessage(b.dataset.prompt));
$('#voiceBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){msg('assistant','الإملاء الصوتي غير مدعوم في هذا المتصفح.');return}const r=new SR();r.lang='ar-SA';r.interimResults=false;r.maxAlternatives=1;$('#voiceBtn').textContent='⏺';r.onresult=e=>{$('#messageInput').value=e.results[0][0].transcript};r.onerror=()=>{$('#voiceBtn').textContent='🎙️'};r.onend=()=>{$('#voiceBtn').textContent='🎙️'};r.start();};
$('#addMemory').onclick=()=>$('#memoryDialog').showModal();$('#memoryForm').addEventListener('submit',async e=>{e.preventDefault();const content=$('#memoryInput').value.trim();if(!content)return;await api('/api/v2/nav/memory',{method:'POST',body:JSON.stringify({content,importance:Number($('#memoryImportance').value)})});$('#memoryInput').value='';$('#memoryDialog').close();await refreshContext(false);});
async function archiveMemory(id){await api(`/api/v2/nav/memory/${id}/archive`,{method:'POST'});await refreshContext(false)}
async function refreshContext(messages=true){try{const d=await api('/api/v2/nav/context');state.context=d.data;if(messages)renderMessages(d.data.messages);renderMemories(d.data.memories);renderCompany(d.data.company);renderCapabilities(d.data);}catch{}}
let streamStarted=false;function wireStream(){if(streamStarted)return;streamStarted=true;const es=new EventSource('/api/v2/events');es.addEventListener('state.changed',()=>refreshContext(false));es.addEventListener('nav.memory.changed',()=>refreshContext(false));es.onerror=()=>{};}
load();