const state={token:sessionStorage.getItem('hq_v2_token')||'',context:null,speak:localStorage.getItem('nav_speak')!=='off',pendingWeather:false,weatherCity:localStorage.getItem('nav_weather_city')||'',sending:false};
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const terminal=new Set(['COMPLETED','FAILED','BLOCKED','CANCELLED','WAITING_FOR_CONNECTION','WAITING_FOR_APPROVAL']);
const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${state.token}`,...options.headers}});const d=await r.json();if(r.status===401||r.status===503&&d.error==='HQ_V2_ACCESS_TOKEN_NOT_CONFIGURED')throw Object.assign(new Error(d.error),{auth:true});if(!r.ok)throw Object.assign(new Error(d.error||'REQUEST_FAILED'),{data:d,status:r.status});return d;};
function speak(text){if(!state.speak||!('speechSynthesis'in window)||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(String(text).slice(0,900));u.lang='ar-SA';u.rate=1.08;window.speechSynthesis.speak(u)}
function msg(role,content,meta=''){const box=$('#messages');const el=document.createElement('article');el.className=`msg ${role}`;el.innerHTML=`${esc(content)}${meta?`<span class="meta">${esc(meta)}</span>`:''}`;box.append(el);box.scrollTop=box.scrollHeight;return el}
function setComposerState(mode='ready',label=''){const form=$('#chatForm'),send=form?.querySelector('.send'),hint=$('#composerStatus');if(!form||!send)return;form.dataset.state=mode;send.disabled=mode==='sending';send.textContent=mode==='sending'?'جاري…':'إرسال';if(hint){hint.textContent=label||(mode==='sending'?'جاري إرسال الأمر لناڤ…':'جاهز · Enter إرسال · Shift+Enter سطر جديد');hint.dataset.state=mode;}}
function setLastCommand(mode='idle',title=''){const box=$('#lastCommandStatus');if(!box)return;box.dataset.state=mode;const strong=box.querySelector('strong'),small=box.querySelector('small');if(mode==='active'){strong.textContent='جاري التنفيذ';small.textContent=title||'أمر ناڤ';}else if(mode==='done'){strong.textContent='اكتمل';small.textContent=title||'تم تنفيذ الأمر';}else if(mode==='error'){strong.textContent='تعذر';small.textContent=title||'راجع المحادثة';}else{strong.textContent='جاهز';small.textContent='ما فيه أمر شغال';}}
function quickTitle(button){return button?.querySelector('.quick-copy strong')?.textContent?.trim()||button?.textContent?.trim()||'أمر سريع';}
function setQuickState(button,mode='idle'){if(!button)return;button.dataset.state=mode;button.setAttribute('aria-pressed',mode==='active'?'true':'false');if(!button.dataset.originalHtml)button.dataset.originalHtml=button.innerHTML;if(mode==='active')button.innerHTML='<span class="quick-icon">…</span><span class="quick-copy"><strong>جاري التنفيذ</strong><small>ناڤ شغال على الأمر</small></span>';else if(mode==='done')button.innerHTML='<span class="quick-icon">✓</span><span class="quick-copy"><strong>تم</strong><small>اكتمل الأمر</small></span>';else if(mode==='error')button.innerHTML='<span class="quick-icon">!</span><span class="quick-copy"><strong>تعذر</strong><small>شوف الرد للتفاصيل</small></span>';else button.innerHTML=button.dataset.originalHtml;}
function settleQuick(button,mode,title){setQuickState(button,mode);setLastCommand(mode,title);setTimeout(()=>{setQuickState(button,'idle');if(mode!=='active')setLastCommand('idle');},mode==='done'?1800:2600);}
async function runQuickPrompt(button){if(button.dataset.state==='active')return;const title=quickTitle(button);document.querySelectorAll('[data-prompt][data-state="active"]').forEach(b=>{if(b!==button)setQuickState(b,'idle')});setQuickState(button,'active');setLastCommand('active',title);try{await sendMessage(button.dataset.prompt);settleQuick(button,'done',title);}catch{settleQuick(button,'error',title);}}
function renderMessages(items){const box=$('#messages');box.innerHTML='';const since=Number(localStorage.getItem('nav_chat_since')||0);const visible=(items||[]).filter(x=>!since||Date.parse(x.created_at||0)>=since);if(!visible.length)msg('assistant','هلا نواف. وش تبيني أخلص لك؟');else visible.slice(-30).forEach(x=>msg(x.role==='user'?'user':'assistant',x.content,x.mode==='company'?'من محرك الشركة':''));}
function renderMemories(items){$('#memories').innerHTML=items?.length?items.map(x=>`<article class="memory"><p>${esc(x.content)}</p><footer><span>أهمية ${x.importance}/5</span><button class="text-btn" data-archive="${x.id}">إخفاء</button></footer></article>`).join(''):'<p class="meta">ما فيه ذاكرة محفوظة داخل تطبيق ناڤ بعد.</p>';document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archiveMemory(b.dataset.archive));}
function renderCompany(c){$('#companyState').innerHTML=`<div class="stat"><strong>${Number(c?.activeTasks||0)}</strong><span>مهام نشطة</span></div><div class="stat"><strong>${Number(c?.attention||0)}</strong><span>تحتاج انتباه</span></div><div class="stat"><strong>${c?.employees?.filter(e=>!['READY','OFFLINE'].includes(e.status)).length||0}</strong><span>يعملون الآن</span></div><div class="stat"><strong>${c?.projects?.filter(p=>p.status==='ACTIVE').length||0}</strong><span>مشاريع نشطة</span></div>`;}
function renderCapabilities(ctx){const backend=(ctx.serverAdapters||[]).map(a=>`<article class="cap"><p><strong>${esc(a.provider)}</strong></p><footer><span>${esc((a.capabilities||[]).join(' · '))}</span><span>داخل HQ</span></footer></article>`).join('');const weather=`<article class="cap"><p><strong>Weather</strong></p><footer><span>live weather · forecast</span><span>داخل ناڤ</span></footer></article>`;const connectors=(ctx.chatgptConnectors||[]).map(a=>`<article class="cap"><p><strong>${esc(a.name)}</strong></p><footer><span>${esc((a.capabilities||[]).join(' · '))}</span><span>ChatGPT فقط</span></footer></article>`).join('');$('#capabilities').innerHTML=backend+weather+connectors;}
async function load(){try{const d=await api('/api/v2/nav/context');state.context=d.data;$('#status').textContent='متصل';$('#status').className='status good';renderMessages(d.data.messages);renderMemories(d.data.memories);renderCompany(d.data.company);renderCapabilities(d.data);wireStream();}catch(error){if(error.auth)return askAuth();$('#status').textContent='تعذر الاتصال';$('#status').className='status bad';msg('assistant','تعذر تحميل ناڤ الآن. جرّب تحديث الصفحة.');}}
function askAuth(){const dlg=$('#authDialog');if(!dlg.open)dlg.showModal();}
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();state.token=$('#tokenInput').value.trim();sessionStorage.setItem('hq_v2_token',state.token);$('#authDialog').close();await load();});
$('#speakToggle').textContent=state.speak?'🔊':'🔇';$('#speakToggle').onclick=()=>{state.speak=!state.speak;localStorage.setItem('nav_speak',state.speak?'on':'off');$('#speakToggle').textContent=state.speak?'🔊':'🔇';if(!state.speak&&'speechSynthesis'in window)window.speechSynthesis.cancel();};
const weatherWords=['كيف الجو','كيف الطقس','الجو','الطقس','درجة الحرارة','حراره','حرارة','weather'];
const isWeatherIntent=text=>weatherWords.some(w=>String(text).toLowerCase().includes(w));
const weatherLabel=code=>({0:'صحو',1:'صحو غالبًا',2:'غائم جزئيًا',3:'غائم',45:'ضباب',48:'ضباب',51:'رذاذ خفيف',53:'رذاذ',55:'رذاذ كثيف',61:'مطر خفيف',63:'مطر',65:'مطر غزير',71:'ثلج خفيف',73:'ثلج',75:'ثلج كثيف',80:'زخات خفيفة',81:'زخات مطر',82:'زخات قوية',95:'عواصف رعدية',96:'عواصف رعدية مع برد',99:'عواصف رعدية قوية'})[code]||'حالة جوية متغيرة';
function cityFromWeatherMessage(text){const m=String(text).match(/(?:في|بـ|ب)\s*([\p{L}\s-]{2,40})$/u);if(m)return m[1].trim().replace(/[؟?!.]+$/,'');return '';}
async function fetchWeather(city){const g=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=ar&format=json`);const gd=await g.json();const place=gd?.results?.[0];if(!place)throw new Error('CITY_NOT_FOUND');const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&timezone=auto`);const wd=await w.json();const c=wd.current;if(!c)throw new Error('WEATHER_UNAVAILABLE');state.weatherCity=place.name||city;localStorage.setItem('nav_weather_city',state.weatherCity);return `الجو الآن في ${place.name||city}: ${weatherLabel(c.weather_code)}، الحرارة ${Math.round(c.temperature_2m)}° والمحسوسة ${Math.round(c.apparent_temperature)}°، والهواء ${Math.round(c.wind_speed_10m)} كم/س.`;}
async function handleWeather(message){let city='';if(state.pendingWeather){city=message;state.pendingWeather=false;}else city=cityFromWeatherMessage(message)||state.weatherCity;if(!city){state.pendingWeather=true;msg('assistant','أكيد. أي مدينة تبي الطقس فيها؟ وبعدها بحفظها عندك للاستخدام الجاي.');return true;}const pending=msg('assistant','أجيب الطقس المباشر…');try{const text=await fetchWeather(city);pending.remove();msg('assistant',text,'بيانات مباشرة · Open-Meteo');speak(text);}catch(error){pending.remove();if(String(error.message).includes('CITY_NOT_FOUND')){state.pendingWeather=true;msg('assistant','ما قدرت أحدد المدينة. اكتب اسم المدينة فقط، مثل: الرياض أو الدمام.');}else msg('assistant','تعذر جلب الطقس المباشر الآن. جرّب بعد شوي.');}return true;}
async function sendMessage(text){const message=String(text||'').trim();if(!message||state.sending)return;state.sending=true;setComposerState('sending');$('#handoff').classList.add('hidden');msg('user',message);$('#messageInput').value='';try{if(state.pendingWeather||isWeatherIntent(message)){await handleWeather(message);return {kind:'weather'};}const pending=msg('assistant','قاعد أنفذ/أفكر…');pending.classList.add('pending');try{const d=await api('/api/v2/nav/chat',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({message})});pending.remove();if(d.kind==='company_task'){msg('assistant',`تم تحويله لمحرك الشركة. ${d.task.title}`,'تنفيذ حقيقي · المتابعة بالخلفية');pollTask(d.task.id);return d;}if(d.kind==='chatgpt_handoff'){msg('assistant',d.text,`يتطلب ${d.provider} داخل ChatGPT`);const h=$('#handoff');h.textContent=`موصل ${d.provider} مربوط بحساب ChatGPT، لكنه مو OAuth داخل تطبيق ناڤ نفسه. نفس الطلب محفوظ وتقدر تنفذه من محادثة ChatGPT.`;h.classList.remove('hidden');return d;}msg('assistant',d.text);speak(d.text);return d;}catch(error){pending.remove();msg('assistant',error.auth?'انتهت جلسة الدخول. أدخل المفتاح من جديد.':'صار خطأ فعلي أثناء التنفيذ وما راح أدّعي نجاحه.');if(error.auth)askAuth();throw error;}}finally{state.sending=false;setComposerState('ready');}}
const taskStatusAr={QUEUED:'بالطابور',ROUTING:'جاري التوجيه',PLANNING:'جاري التخطيط',WORKING:'قيد التنفيذ',RESEARCHING:'جاري البحث',REVIEWING:'جاري المراجعة',WAITING_FOR_CONNECTION:'بانتظار ربط',WAITING_FOR_APPROVAL:'بانتظار موافقتك',BLOCKED:'متوقفة',COMPLETED:'مكتملة',FAILED:'فشلت',CANCELLED:'ملغاة'};function taskStatusText(v){return taskStatusAr[v]||v||'غير معروف';}
async function pollTask(id){const started=Date.now();let last='';while(Date.now()-started<360000){await new Promise(r=>setTimeout(r,2500));try{const d=await api(`/api/v2/tasks/${id}`),t=d.task;if(t.status!==last){last=t.status;msg('assistant',`حالة المهمة: ${taskStatusText(t.status)}`,'متابعة مباشرة');}if(terminal.has(t.status)){if(t.result?.summary){msg('assistant',t.result.summary,`النتيجة: ${taskStatusText(t.status)}`);speak(t.result.summary)}else if(t.error_message)msg('assistant',t.error_message,`النتيجة: ${taskStatusText(t.status)}`);await refreshContext(false);return;}}catch{return}}msg('assistant','المهمة ما زالت مستمرة بالخلفية. تقدر تتابعها من صفحة المهام في NAWAF HQ.');}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();sendMessage($('#messageInput').value).catch(()=>{})});
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>runQuickPrompt(b));
async function runNavAction(button){if(!button||button.dataset.state==='active')return;const action=button.dataset.navAction,title=quickTitle(button);setQuickState(button,'active');setLastCommand('active',title);try{let opened=false;if(action==='open-whatsapp'){window.open('https://web.whatsapp.com/','_blank','noopener,noreferrer');opened=true;}else if(action==='open-vscode'){location.href='vscode://';opened=true;}else if(action==='open-mueen'){const projects=state.context?.company?.projects||[];const p=projects.find(x=>['mueen','معين','مُعين'].includes(String(x.id||'').toLowerCase())||String(x.name_ar||'').includes('معين')||String(x.name_ar||'').includes('مُعين'));const url=p?.metadata?.admin_url||p?.live_url||'/#projects';window.open(url,'_blank','noopener,noreferrer');opened=true;}if(opened){settleQuick(button,'done',title);}else throw new Error('ACTION_NOT_AVAILABLE');}catch{settleQuick(button,'error',title);}}
document.querySelectorAll('[data-nav-action]').forEach(b=>b.onclick=()=>runNavAction(b));
const newChatBtn=$('#newChatBtn');if(newChatBtn)newChatBtn.onclick=()=>{localStorage.setItem('nav_chat_since',String(Date.now()));renderMessages([]);$('#messageInput')?.focus();setLastCommand('idle');};
setComposerState('ready');
$('#voiceBtn').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){msg('assistant','الإملاء الصوتي غير مدعوم في هذا المتصفح.');return}const r=new SR();r.lang='ar-SA';r.interimResults=false;r.maxAlternatives=1;const btn=$('#voiceBtn');btn.textContent='⏺';btn.classList.add('listening');setComposerState('listening','قاعد أسمعك…');r.onresult=e=>{$('#messageInput').value=e.results[0][0].transcript;$('#messageInput').focus()};r.onerror=()=>{};r.onend=()=>{btn.textContent='🎙️';btn.classList.remove('listening');setComposerState('ready')};r.start();};
$('#addMemory').onclick=()=>$('#memoryDialog').showModal();$('#memoryForm').addEventListener('submit',async e=>{e.preventDefault();const content=$('#memoryInput').value.trim();if(!content)return;await api('/api/v2/nav/memory',{method:'POST',body:JSON.stringify({content,importance:Number($('#memoryImportance').value)})});$('#memoryInput').value='';$('#memoryDialog').close();await refreshContext(false);});
async function archiveMemory(id){await api(`/api/v2/nav/memory/${id}/archive`,{method:'POST'});await refreshContext(false)}
async function refreshContext(messages=true){try{const d=await api('/api/v2/nav/context');state.context=d.data;if(messages)renderMessages(d.data.messages);renderMemories(d.data.memories);renderCompany(d.data.company);renderCapabilities(d.data);}catch{}}
let streamStarted=false;function wireStream(){if(streamStarted)return;streamStarted=true;const es=new EventSource('/api/v2/events');es.addEventListener('state.changed',()=>refreshContext(false));es.addEventListener('nav.memory.changed',()=>refreshContext(false));es.onerror=()=>{};}
load();