const hqToken=()=>sessionStorage.getItem('hq_v2_token')||'';
const hqEsc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const activeStates=new Set(['QUEUED','ROUTING','PLANNING','WORKING','RESEARCHING','REVIEWING','PAUSED_EXTERNAL']);
async function hqSnap(){const t=hqToken();if(!t)return null;const r=await fetch('/api/v2/snapshot',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});if(!r.ok)return null;return (await r.json()).data}
function dayPart(){const h=new Date().getHours();return h<12?'صباح الخير':h<18?'مساء الخير':'مساء النور'}
function projectTone(id=''){id=String(id).toLowerCase();return id.includes('mueen')?'mueen':id.includes('qaddha')?'qaddha':id.includes('nav')?'nav':'default'}
function projectCard(p,tasks){const projectTasks=tasks.filter(t=>t.project_id===p.id),done=projectTasks.filter(t=>t.status==='COMPLETED').length,progress=projectTasks.length?Math.round(done/projectTasks.length*100):0;const admin=p.metadata?.admin_url;return `<article class="hq4-project ${projectTone(p.id)}"><div class="hq4-project-art"><span>${hqEsc((p.name_ar||p.name_en||'P').slice(0,1))}</span></div><div class="hq4-project-body"><div class="hq4-project-top"><div><small>${hqEsc(p.status||'ACTIVE')}</small><h3>${hqEsc(p.name_ar||p.name_en||p.id)}</h3></div><b>${progress}%</b></div><p>${hqEsc(p.name_en||'مشروع داخل NAWAF HQ')}</p><div class="hq4-progress"><i style="width:${progress}%"></i></div><div class="hq4-project-meta"><span>${projectTasks.length} مهمة</span><span>${done} مكتملة</span></div><div class="hq4-project-actions">${p.live_url?`<a href="${hqEsc(p.live_url)}" target="_blank" rel="noreferrer">فتح المشروع</a>`:''}${admin?`<a href="${hqEsc(admin)}" target="_blank" rel="noreferrer">لوحة التحكم</a>`:''}<button data-hq-route="projects">التفاصيل</button></div></div></article>`}
function employeeRow(e){const active=!['READY','OFFLINE'].includes(e.status);return `<button class="hq4-person" data-employee="${hqEsc(e.id)}"><span class="hq4-avatar">${hqEsc((e.name_ar||'م')[0])}</span><span><strong>${hqEsc(e.name_ar)}</strong><small>${hqEsc(e.role||e.department||'الفريق')}</small></span><em class="${active?'busy':'ready'}">${active?'يعمل الآن':'متاح'}</em></button>`}
function activityRow(t){return `<div class="hq4-activity"><span class="hq4-dot ${String(t.status).toLowerCase()}"></span><div><strong>${hqEsc(t.title)}</strong><small>${hqEsc(t.status)} · ${new Date(t.updated_at||t.created_at).toLocaleString('ar-SA')}</small></div></div>`}
function kpi(icon,label,value,sub,tone='blue'){return `<article class="hq4-kpi ${tone}"><span class="hq4-kpi-icon">${icon}</span><div><small>${label}</small><strong>${value}</strong><em>${sub}</em></div></article>`}
function buildHome(view,data){if(!view||view.dataset.hq4==='1')return;const originalHero=view.querySelector('.hero');if(!originalHero)return;view.dataset.hq4='1';view.className='hq4-view';
const form=originalHero.querySelector('#commandForm');const active=(data.tasks||[]).filter(t=>activeStates.has(t.status));const completed=(data.tasks||[]).filter(t=>t.status==='COMPLETED');const approvals=(data.approvals||[]).length;const working=(data.employees||[]).filter(e=>!['READY','OFFLINE'].includes(e.status)).length;const projects=(data.projects||[]).slice(0,4);const recent=[...(data.tasks||[])].sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at)).slice(0,5);const now=new Date();
view.innerHTML=`<div class="hq4-shell">
<section class="hq4-hero"><div class="hq4-hero-shade"></div><div class="hq4-hero-copy"><span class="hq4-kicker">NAWAF HQ · COMPANY OPERATING SYSTEM</span><h1>${dayPart()} <b>نواف</b></h1><p>أفكارك، فريقك، ومشاريعك — تنفيذ حقيقي في مكان واحد.</p><div class="hq4-quote">“المستقبل ما ينتظر أحد… إحنا نبنيه.”</div><div class="hq4-hero-actions"><button class="hq4-primary" data-hq-route="command">مراجعة اليوم</button><button data-hq-route="projects">مشاريعي</button><button data-hq-route="employees">إدارة الفريق</button></div></div><div class="hq4-date"><small>${now.toLocaleDateString('ar-SA',{weekday:'long',day:'numeric',month:'long'})}</small><strong>${now.toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})}</strong><span>NAWAF HQ · LIVE</span></div></section>
<section class="hq4-command"><div><span>✦</span><strong>وش تبغى الشركة تسوي؟</strong><small>اكتب أمر طبيعي، والنظام يوجهه للموظف المناسب.</small></div><div id="hq4-command-slot"></div></section>
<section class="hq4-kpis">${kpi('◎','الموظفون',data.employees?.length||0,`${working} يعملون الآن`,'blue')}${kpi('◇','المشاريع',data.projects?.length||0,'محفظة الشركة','violet')}${kpi('✓','المهام المكتملة',completed.length,'نتائج موثقة','green')}${kpi('↻','المهام الجارية',active.length,'تنفيذ بالخلفية','cyan')}${kpi('!','تحتاج تدخلك',approvals,'موافقات وقرارات','amber')}</section>
<div class="hq4-main-grid"><section class="hq4-card hq4-projects-card"><header><div><small>PORTFOLIO</small><h2>مشاريع الشركة</h2></div><button data-hq-route="projects">عرض الكل</button></header><div class="hq4-project-grid">${projects.map(p=>projectCard(p,data.tasks||[])).join('')||'<p class="empty">لا توجد مشاريع.</p>'}</div></section><section class="hq4-card hq4-team-card"><header><div><small>WORKFORCE</small><h2>الفريق الآن</h2></div><button data-hq-route="employees">إدارة</button></header><div class="hq4-team-list">${(data.employees||[]).slice(0,7).map(employeeRow).join('')}</div></section></div>
<div class="hq4-lower-grid"><section class="hq4-card"><header><div><small>LIVE OPERATIONS</small><h2>النشاط الأخير</h2></div><button data-hq-route="activity">السجل</button></header><div class="hq4-activity-list">${recent.map(activityRow).join('')||'<p class="empty">لا نشاط حتى الآن.</p>'}</div></section><section class="hq4-card hq4-ops"><header><div><small>BACKGROUND</small><h2>عمليات الخلفية</h2></div><span class="hq4-live">● مباشر</span></header><div class="hq4-ops-grid"><div><b>${active.length}</b><span>مهام تعمل</span></div><div><b>${completed.length}</b><span>نتائج مكتملة</span></div><div><b>${approvals}</b><span>قرارات تنتظرك</span></div><div><b>${working}</b><span>موظفون نشطون</span></div></div><p>كل الأرقام هنا من الحالة الفعلية للنظام، بدون نشاط وهمي.</p></section></div>
</div>`;
if(form){form.classList.add('hq4-command-form');view.querySelector('#hq4-command-slot').append(form)}
view.querySelectorAll('[data-hq-route]').forEach(btn=>btn.addEventListener('click',()=>document.querySelector(`.nav-btn[data-route="${btn.dataset.hqRoute}"]`)?.click()));
}
async function tryBuildHome(){if((location.hash||'#home')!=='#home')return;const view=document.querySelector('#view');if(!view||view.dataset.hq4==='1')return;const data=await hqSnap();if(data)buildHome(view,data)}
const hqObserver=new MutationObserver(()=>{clearTimeout(window.__hq4);window.__hq4=setTimeout(tryBuildHome,60)});hqObserver.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>setTimeout(tryBuildHome,100));document.addEventListener('DOMContentLoaded',()=>setTimeout(tryBuildHome,120));