const token=()=>sessionStorage.getItem('hq_v2_token')||'';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const activeStates=new Set(['QUEUED','ROUTING','PLANNING','WORKING','RESEARCHING','REVIEWING','PAUSED_EXTERNAL']);
async function snap(){const t=token();if(!t)return null;const r=await fetch('/api/v2/snapshot',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});if(!r.ok)return null;return (await r.json()).data;}
function partOfDay(){const h=new Date().getHours();return h<12?'صباح الخير':h<18?'مساء الخير':'مساء النور';}
function projectCard(p){const id=String(p.id||'').toLowerCase(), cls=id.includes('mueen')?'mueen':id.includes('qaddha')?'qaddha':id.includes('nav')?'nav':'';const admin=p.metadata?.admin_url;return `<article class="v3-project-card ${cls}"><small>${esc(p.status||'ACTIVE')}</small><h4>${esc(p.name_ar||p.name_en||p.id)}</h4><p>${esc(p.name_en||'مشروع داخل NAWAF HQ')}</p><div class="v3-project-actions"><button class="accent" data-project-control="${esc(p.id)}">لوحة التحكم</button>${admin?`<a href="${esc(admin)}" target="_blank" rel="noreferrer">لوحة الإدارة</a>`:''}${p.live_url?`<a href="${esc(p.live_url)}" target="_blank" rel="noreferrer">فتح المشروع</a>`:''}</div></article>`}
function buildShell(view,data){if(!view||view.dataset.v3Built==='1')return;const hero=view.querySelector('.hero'),metrics=view.querySelector('.metrics'),grid=view.querySelector('.grid-2'),daily=view.querySelector('.daily-employee-note'),last=[...view.children].find(x=>x.classList?.contains('section-card')&&!grid?.contains(x));if(!hero||!metrics||!grid)return;view.dataset.v3Built='1';view.classList.add('v3-home-active');
const active=(data.tasks||[]).filter(t=>activeStates.has(t.status));const completed=(data.tasks||[]).filter(t=>t.status==='COMPLETED');const working=(data.employees||[]).filter(e=>!['READY','OFFLINE'].includes(e.status)).length;const approvals=(data.approvals||[]).length;const projects=(data.projects||[]).slice(0,3);
const shell=document.createElement('div');shell.className='v3-home-shell';
const heroGrid=document.createElement('section');heroGrid.className='v3-hero-grid';heroGrid.innerHTML=`<div class="v3-main-hero"><span class="v3-kicker">NAWAF HQ · AI COMPANY OS</span><h2>${partOfDay()} يا نواف</h2><p>من هنا تشوف شركتك، مشاريعك، فريقك، وشغل الخلفية — وتصدر أي أمر من مكان واحد.</p><div class="v3-hero-actions"><button class="v3-pill primary" data-route="command">أصدر أمر جديد</button><button class="v3-pill" data-route="projects">افتح المشاريع</button><button class="v3-pill" data-route="employees">الفريق</button></div></div><aside class="v3-side-card"><div class="v3-daily-slot"></div><div class="v3-mini-stats"><div class="v3-mini-stat"><strong>${working}</strong><span>يعملون الآن</span></div><div class="v3-mini-stat"><strong>${active.length}</strong><span>مهام نشطة</span></div><div class="v3-mini-stat"><strong>${approvals}</strong><span>تحتاج موافقة</span></div><div class="v3-mini-stat"><strong>${completed.length}</strong><span>مكتملة</span></div></div></aside>`;
const command=document.createElement('section');command.className='v3-command-wrap v3-section';command.innerHTML='<div class="v3-command-title"><h3>مركز الأوامر السريع</h3><span>نفّذ مباشرة من هنا</span></div>';command.append(hero);
const projectsSection=document.createElement('section');projectsSection.className='v3-section';projectsSection.innerHTML=`<div class="v3-section-head"><h3>مشاريعنا</h3><button data-route="projects">عرض الكل ←</button></div><div class="v3-projects">${projects.map(projectCard).join('')||'<p class="empty">لا توجد مشاريع.</p>'}</div>`;
const work=document.createElement('section');work.className='v3-work-grid';while(grid.firstChild)work.append(grid.firstChild);
const bottom=document.createElement('section');bottom.className='v3-bottom-grid';if(last)bottom.append(last);
if(daily){heroGrid.querySelector('.v3-daily-slot').append(daily)}else heroGrid.querySelector('.v3-daily-slot').innerHTML='<div class="daily-copy"><span class="daily-kicker">رسالة اليوم</span><strong>الفريق</strong><p>كل شيء واضح قدامك. إذا فيه شيء يحتاج تدخل منك بيظهر هنا مباشرة.</p></div>';
metrics.remove();grid.remove();if(last)last.remove();
shell.append(heroGrid,command,metrics,projectsSection,work,bottom);view.prepend(shell);
}
async function tryBuild(){if(location.hash&&location.hash!=='#home')return;const view=document.querySelector('#view');if(!view||view.dataset.v3Built==='1')return;const data=await snap();if(!data)return;buildShell(view,data)}
const obs=new MutationObserver(()=>{clearTimeout(window.__v3home);window.__v3home=setTimeout(tryBuild,70)});obs.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>{const v=document.querySelector('#view');if(v){delete v.dataset.v3Built;v.classList.remove('v3-home-active')}setTimeout(tryBuild,120)});document.addEventListener('DOMContentLoaded',()=>setTimeout(tryBuild,150));