const BASE=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const KEY=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'';
function send(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
async function request(path,options={}){if(!BASE||!KEY)throw new Error('CLOUD_NOT_CONFIGURED');const r=await fetch(BASE+'/rest/v1/'+path,{...options,headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error('BACKEND_'+r.status);return d}
async function readBody(req){let raw='';for await(const c of req)raw+=c;if(!raw)return {};try{return JSON.parse(raw)}catch{return {}}}
function stamp(o){if(!o||typeof o!=='object')return 0;for(const k of ['updatedAt','lastRunAt','executionFinishedAt','executionStartedAt','createdAt']){const t=Date.parse(o[k]||'');if(Number.isFinite(t))return t}return 0}
function mergeList(current=[],incoming=[]){const m=new Map();for(const x of Array.isArray(current)?current:[])if(x&&x.id)m.set(x.id,x);for(const x of Array.isArray(incoming)?incoming:[])if(x&&x.id){const old=m.get(x.id);if(!old)m.set(x.id,x);else{const os=stamp(old),ns=stamp(x);m.set(x.id,ns>os?{...old,...x}:{...x,...old})}}return [...m.values()]}
function mergeProtectedState(current={},incoming={}){const out={...current,...incoming};for(const k of ['employees','projects','tasks','reports','activity','approvals','meetings','goals'])out[k]=mergeList(current[k],incoming[k]);out.settings={...(current.settings||{}),...(incoming.settings||{})};return out}
function recoverLegacyPrivateRepoFailure(state){if(!state||typeof state!=='object')return false;const tasks=Array.isArray(state.tasks)?state.tasks:[];let changed=false;const ts=new Date().toISOString();for(const task of tasks){const reason=String(task?.blockedReason||'');if(!task?.id||task.privateRepoAuthRetryAt||!reason.includes('PROJECT_EXECUTION_FAILED'))continue;task.lastFailure={reason,at:task.executionFinishedAt||task.updatedAt||ts};task.privateRepoAuthRetryAt=ts;task.status='READY';task.progress=0;task.updatedAt=ts;delete task.blockedReason;delete task.executionStartedAt;const e=(state.employees||[]).find(x=>x.id===task.employeeId);if(e){e.status='READY';e.task='';e.updatedAt=ts}changed=true}if(changed){state.activity=Array.isArray(state.activity)?state.activity:[];state.activity.unshift({id:'recovery-'+Date.now().toString(36),text:'إعادة محاولة تلقائية لمهمة تعثرت سابقًا بعد إصلاح الوصول للمستودعات الخاصة.',type:'REAL',at:ts,updatedAt:ts})}return changed}
export async function loadCloudState(){const rows=await request('hq_state?id=eq.main&select=data,updated_at');const state=rows?.[0]?.data||null;let updatedAt=rows?.[0]?.updated_at||null;if(state&&recoverLegacyPrivateRepoFailure(state)){const payload={id:'main',data:state,updated_at:new Date().toISOString()};await request('hq_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});updatedAt=payload.updated_at}return {state,updatedAt}}
export async function saveCloudState(state,expectedUpdatedAt=''){if(!state||typeof state!=='object')throw new Error('INVALID_STATE');const c=await loadCloudState();if(expectedUpdatedAt&&c.updatedAt&&String(expectedUpdatedAt)!==String(c.updatedAt)){const err=new Error('STATE_CONFLICT');err.current=c;throw err}const merged=mergeProtectedState(c.state||{},state);const payload={id:'main',data:merged,updated_at:new Date().toISOString()};await request('hq_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});return {updatedAt:payload.updated_at,state:merged}}
export async function handleStateApi(req,res){try{if(req.method==='GET'){const c=await loadCloudState();return send(res,200,{ok:true,...c})}if(req.method==='POST'){const b=await readBody(req);if(!b.state||typeof b.state!=='object')return send(res,400,{ok:false,error:'INVALID_STATE'});try{const saved=await saveCloudState(b.state,b.baseUpdatedAt||'');return send(res,200,{ok:true,updatedAt:saved.updatedAt})}catch(e){if(e?.message==='STATE_CONFLICT')return send(res,409,{ok:false,error:'STATE_CONFLICT',state:e.current?.state,updatedAt:e.current?.updatedAt});throw e}}return send(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'})}catch(e){console.error('state-cloud',e?.message||e);return send(res,503,{ok:false,error:String(e?.message||'STATE_BACKEND_ERROR')})}}
export function cloudConfigured(){return !!(BASE&&KEY)}
