const BASE=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const KEY=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||'';
const SARA_RECOVERY_TASK_ID='tmu35pdebvh2d';
function send(res,status,body){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
async function request(path,options={}){if(!BASE||!KEY)throw new Error('CLOUD_NOT_CONFIGURED');const r=await fetch(BASE+'/rest/v1/'+path,{...options,headers:{apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json',...(options.headers||{})}});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error('BACKEND_'+r.status);return d}
async function readBody(req){let raw='';for await(const c of req)raw+=c;if(!raw)return {};try{return JSON.parse(raw)}catch{return {}}}
function stamp(o){if(!o||typeof o!=='object')return 0;for(const k of ['updatedAt','lastRunAt','executionFinishedAt','executionStartedAt','createdAt']){const t=Date.parse(o[k]||'');if(Number.isFinite(t))return t}return 0}
function mergeList(current=[],incoming=[]){const m=new Map();for(const x of Array.isArray(current)?current:[])if(x&&x.id)m.set(x.id,x);for(const x of Array.isArray(incoming)?incoming:[])if(x&&x.id){const old=m.get(x.id);if(!old)m.set(x.id,x);else{const os=stamp(old),ns=stamp(x);m.set(x.id,ns>os?{...old,...x}:{...x,...old})}}return [...m.values()]}
function mergeProtectedState(current={},incoming={}){const out={...current,...incoming};for(const k of ['employees','projects','tasks','reports','activity','approvals','meetings','goals','connectionRequests','secretaryBriefs'])out[k]=mergeList(current[k],incoming[k]);out.settings={...(current.settings||{}),...(incoming.settings||{})};out.projectMemory={...(current.projectMemory||{}),...(incoming.projectMemory||{})};out.secretarySeen=[...new Set([...(current.secretarySeen||[]),...(incoming.secretarySeen||[])])].slice(0,250);out.trading={...(current.trading||{}),...(incoming.trading||{})};return out}
function normalizeOperationalState(state){
 if(!state||typeof state!=='object')return false;let changed=false;const ts=new Date().toISOString();
 const tasks=Array.isArray(state.tasks)?state.tasks:[];
 for(const t of tasks){if(t?.status==='COMPLETED'){for(const k of ['blockedReason','blockerType','requiredTools','connectionRequest'])if(k in t){delete t[k];changed=true}if(t.progress!==100){t.progress=100;changed=true}}}
 if(Array.isArray(state.connectionRequests))for(const r of state.connectionRequests){const t=tasks.find(x=>x.id===r.taskId);if(t?.status==='COMPLETED'&&['PENDING','APPROVED'].includes(r.status)){r.status='RESOLVED';r.resolvedAt=ts;r.updatedAt=ts;r.note=r.note||'تم حل الحاجة للأداة ضمن مسار التنفيذ الحالي.';changed=true}}
 const activeStatuses=new Set(['WORKING','RESEARCHING','REVIEWING','WAITING_FOR_CONNECTION','WAITING_FOR_NAWAF','BLOCKED_BY_TOOL','BLOCKED','PAUSED']);
 for(const e of (state.employees||[])){
   const active=tasks.filter(t=>t.employeeId===e.id&&activeStatuses.has(t.status)).sort((a,b)=>stamp(b)-stamp(a))[0];
   if(active){if(e.status!==active.status||e.task!==(active.title||'')){e.status=active.status;e.task=active.title||'';e.updatedAt=ts;changed=true}}
   else if(e.status!=='READY'||e.task){e.status='READY';e.task='';e.updatedAt=ts;changed=true}
 }
 return changed;
}
function cleanTestPollution(state){if(!state||typeof state!=='object')return false;const hasQa=x=>/QA-AUTO-/i.test(String(x||'')),isQa=x=>hasQa(x?.title)||hasQa(x?.details)||hasQa(x?.text)||hasQa(x?.content)||hasQa(x?.result),qaIds=new Set((state.tasks||[]).filter(isQa).map(x=>String(x.id)));let changed=false;for(const key of ['tasks','reports','activity','secretaryBriefs']){if(!Array.isArray(state[key]))continue;const before=state[key].length;state[key]=state[key].filter(x=>!isQa(x));if(state[key].length!==before)changed=true}for(const e of (state.employees||[])){if(hasQa(e?.task)){e.task='';if(!['PAUSED'].includes(e.status))e.status='READY';e.updatedAt=new Date().toISOString();changed=true}}if(Array.isArray(state.secretarySeen)){const before=state.secretarySeen.length;state.secretarySeen=state.secretarySeen.filter(x=>![...qaIds].some(id=>String(x).startsWith(id+':'))&&!hasQa(x));if(state.secretarySeen.length!==before)changed=true}return changed}
function resetForRetry(state,task,marker,text,ts){const reason=String(task.blockedReason||'');task.lastFailure={reason,at:task.executionFinishedAt||task.updatedAt||ts};task[marker]=ts;task.status='READY';task.progress=0;task.updatedAt=ts;delete task.blockedReason;delete task.blockerType;delete task.requiredTools;delete task.executionStartedAt;const e=(state.employees||[]).find(x=>x.id===task.employeeId);if(e){e.status='READY';e.task='';e.updatedAt=ts}state.activity=Array.isArray(state.activity)?state.activity:[];state.activity.unshift({id:'recovery-'+Date.now().toString(36)+Math.random().toString(36).slice(2,5),text,type:'REAL',at:ts,updatedAt:ts})}
function recoverKnownWorkerFailures(state){if(!state||typeof state!=='object')return false;const tasks=Array.isArray(state.tasks)?state.tasks:[];let changed=false;const ts=new Date().toISOString();for(const task of tasks){if(!task?.id)continue;const reason=String(task.blockedReason||'');if(task.id===SARA_RECOVERY_TASK_ID&&task.status!=='COMPLETED'&&reason.includes('cache_creation_tokens')&&!task.runtimeCompatRetryAt){resetForRetry(state,task,'runtimeCompatRetryAt','إعادة محاولة مهمة سارة الأصلية بعد إصلاح توافق OpenHands وLiteLLM.',ts);changed=true;continue}if(task.id===SARA_RECOVERY_TASK_ID&&task.status!=='COMPLETED'&&(reason.includes('403')||reason.includes('Write access to repository not granted'))&&!task.githubTokenRefreshRetryAt){resetForRetry(state,task,'githubTokenRefreshRetryAt','إعادة محاولة مهمة سارة الأصلية بعد تحديث GitHub token بصلاحية المستودع الخاص.',ts);changed=true;continue}if(task.id===SARA_RECOVERY_TASK_ID&&task.status!=='COMPLETED'&&!task.verifiedRuntimeRetryAt){resetForRetry(state,task,'verifiedRuntimeRetryAt','إعادة المحاولة النهائية لمهمة سارة الأصلية بعد إصلاح المزامنة والوصول للمستودع الخاص ومحرك التنفيذ.',ts);changed=true;continue}if(reason.includes('PROJECT_EXECUTION_FAILED')&&!task.privateRepoAuthRetryAt){resetForRetry(state,task,'privateRepoAuthRetryAt','إعادة محاولة تلقائية بعد إصلاح الوصول للمستودعات الخاصة.',ts);changed=true;continue}if(reason.includes('STATE_CONFLICT')&&!task.syncConflictRetryAt){resetForRetry(state,task,'syncConflictRetryAt','إعادة محاولة تلقائية بعد إصلاح تعارض المزامنة قبل التنفيذ.',ts);changed=true}}return changed}
function removeTaskFromState(state,id){if(!state||typeof state!=='object')state={};const task=(state.tasks||[]).find(t=>String(t.id)===String(id));state.tasks=Array.isArray(state.tasks)?state.tasks.filter(t=>String(t.id)!==String(id)):[];state.reports=Array.isArray(state.reports)?state.reports.filter(r=>String(r.sourceTaskId||'')!==String(id)):[];state.approvals=Array.isArray(state.approvals)?state.approvals.filter(a=>String(a.taskId||a.sourceTaskId||'')!==String(id)):[];state.connectionRequests=Array.isArray(state.connectionRequests)?state.connectionRequests.filter(a=>String(a.taskId||'')!==String(id)):[];state.secretaryBriefs=Array.isArray(state.secretaryBriefs)?state.secretaryBriefs.filter(b=>String(b.taskId||'')!==String(id)):[];if(Array.isArray(state.secretarySeen))state.secretarySeen=state.secretarySeen.filter(x=>!String(x).startsWith(String(id)+':'));if(task&&Array.isArray(state.employees)){const e=state.employees.find(x=>x.id===task.employeeId);if(e&&(e.task===task.title||e.task===task.details||['WORKING','RESEARCHING','REVIEWING','BLOCKED_BY_TOOL','WAITING_FOR_CONNECTION','WAITING_FOR_NAWAF','BLOCKED','PAUSED'].includes(e.status))){e.task='';e.status='READY';e.updatedAt=new Date().toISOString()}}state.updatedAt=new Date().toISOString();return state}
export async function loadCloudState(){const rows=await request('hq_state?id=eq.main&select=data,updated_at');const state=rows?.[0]?.data||null;let updatedAt=rows?.[0]?.updated_at||null;const recovered=state?recoverKnownWorkerFailures(state):false,cleaned=state?cleanTestPollution(state):false,normalized=state?normalizeOperationalState(state):false;if(state&&(recovered||cleaned||normalized)){const payload={id:'main',data:state,updated_at:new Date().toISOString()};await request('hq_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});updatedAt=payload.updated_at}return {state,updatedAt}}
export async function saveCloudState(state,expectedUpdatedAt=''){if(!state||typeof state!=='object')throw new Error('INVALID_STATE');const c=await loadCloudState();if(expectedUpdatedAt&&c.updatedAt&&String(expectedUpdatedAt)!==String(c.updatedAt)){const err=new Error('STATE_CONFLICT');err.current=c;throw err}const merged=mergeProtectedState(c.state||{},state);cleanTestPollution(merged);normalizeOperationalState(merged);const payload={id:'main',data:merged,updated_at:new Date().toISOString()};await request('hq_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});return {updatedAt:payload.updated_at,state:merged}}
export async function deleteCloudTask(taskId){const id=String(taskId||'').trim();if(!id)throw new Error('TASK_ID_REQUIRED');const c=await loadCloudState();const state=removeTaskFromState(c.state||{},id);normalizeOperationalState(state);const payload={id:'main',data:state,updated_at:new Date().toISOString()};await request('hq_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});return {updatedAt:payload.updated_at,state}}
export async function handleStateApi(req,res){try{if(req.method==='GET'){const c=await loadCloudState();return send(res,200,{ok:true,...c})}if(req.method==='POST'){const b=await readBody(req);if(b.deleteTaskId){const deleted=await deleteCloudTask(b.deleteTaskId);return send(res,200,{ok:true,deletedTaskId:String(b.deleteTaskId),state:deleted.state,updatedAt:deleted.updatedAt})}if(!b.state||typeof b.state!=='object')return send(res,400,{ok:false,error:'INVALID_STATE'});try{const saved=await saveCloudState(b.state,b.baseUpdatedAt||'');return send(res,200,{ok:true,updatedAt:saved.updatedAt})}catch(e){if(e?.message==='STATE_CONFLICT')return send(res,409,{ok:false,error:'STATE_CONFLICT',state:e.current?.state,updatedAt:e.current?.updatedAt});throw e}}return send(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'})}catch(e){console.error('state-cloud',e?.message||e);return send(res,503,{ok:false,error:String(e?.message||'STATE_BACKEND_ERROR')})}}
export function cloudConfigured(){return !!(BASE&&KEY)}
