const ALPACA_BASE='https://paper-api.alpaca.markets';
const KEY_ID=()=>String(process.env.ALPACA_PAPER_KEY_ID||'').trim();
const SECRET=()=>String(process.env.ALPACA_PAPER_SECRET_KEY||'').trim();

export function alpacaPaperConfigured(){return Boolean(KEY_ID()&&SECRET())}
function now(){return new Date().toISOString()}
function textOf(t){return String(`${t?.title||''} ${t?.details||''}`).toLowerCase()}
function headers(){return {'APCA-API-KEY-ID':KEY_ID(),'APCA-API-SECRET-KEY':SECRET(),'Content-Type':'application/json'}}
async function call(path,options={}){const r=await fetch(ALPACA_BASE+path,{...options,headers:{...headers(),...(options.headers||{})},signal:AbortSignal.timeout(30000)});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch{data={raw}}if(!r.ok){const e=new Error(`ALPACA_PAPER_HTTP_${r.status}: ${data?.message||raw||'request failed'}`);e.status=r.status;throw e}return data}
function ensureConnectionRequest(state,task){state.connectionRequests=Array.isArray(state.connectionRequests)?state.connectionRequests:[];let req=state.connectionRequests.find(x=>x.provider==='alpaca-paper'&&x.taskId===task.id&&!['DECLINED','CONNECTED'].includes(x.status));if(!req){req={id:'conn-'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),provider:'alpaca-paper',providerName:'Alpaca Paper Trading',taskId:task.id,employeeId:task.employeeId||'',status:'PENDING',reason:'هذه المهمة تحتاج محفظة تداول ورقية حقيقية للتنفيذ والمتابعة.',permissions:['قراءة حساب Paper فقط','قراءة المراكز والأوامر الورقية','إنشاء أوامر Paper فقط عند وجود أمر صريح من نواف'],setupUrl:'https://app.alpaca.markets/paper/dashboard/overview',requiredSecrets:['ALPACA_PAPER_KEY_ID','ALPACA_PAPER_SECRET_KEY'],createdAt:now(),updatedAt:now()};state.connectionRequests.unshift(req)}task.connectionRequestId=req.id;return req}
function explicitSide(text){if(/\b(sell|short)\b|بيع|بع\s/.test(text))return 'sell';if(/\b(buy|long)\b|شراء|اشتر|اشتري/.test(text))return 'buy';return ''}
function symbolFrom(text){const m=text.match(/\b[A-Z]{1,5}\b/);return m?.[0]||''}
function amountFrom(text){const m=text.match(/(?:\$|usd\s*)?([0-9]+(?:\.[0-9]+)?)\s*(?:\$|usd|دولار)/i);return m?Number(m[1]):null}
function qtyFrom(text){const m=text.match(/([0-9]+(?:\.[0-9]+)?)\s*(?:سهم|أسهم|shares?|share)/i);return m?Number(m[1]):null}

export function resumeConnectedTasks(state){if(!alpacaPaperConfigured()||!state||typeof state!=='object')return false;let changed=false;const ts=now();state.connectionRequests=Array.isArray(state.connectionRequests)?state.connectionRequests:[];for(const req of state.connectionRequests){if(req.provider==='alpaca-paper'&&['PENDING','APPROVED'].includes(req.status)){req.status='CONNECTED';req.connectedAt=ts;req.updatedAt=ts;const task=(state.tasks||[]).find(t=>t.id===req.taskId);if(task&&task.status==='WAITING_FOR_CONNECTION'){task.status='READY';task.progress=0;task.updatedAt=ts;delete task.blockedReason;delete task.blockerType;const e=(state.employees||[]).find(x=>x.id===task.employeeId);if(e){e.status='READY';e.task='';e.updatedAt=ts}}changed=true}}
return changed}

export async function executeTradingTask(task,state){const text=textOf(task);if(!alpacaPaperConfigured()){const req=ensureConnectionRequest(state,task);return {status:'NEEDS_CONNECTION',summary:'راكان يحتاج ربط Alpaca Paper Trading لإكمال هذه المهمة. تم إنشاء طلب ربط بدل إيقاف المهمة كأداة ناقصة.',deliverable:'بعد موافقة نواف وربط بيانات Alpaca Paper على الخادم، ستعود نفس المهمة إلى READY وتكمل تلقائيًا.',evidence:[`Connection request: ${req.id}`],nextActions:['وافق على طلب الربط','أضف مفاتيح Alpaca Paper في أسرار الخادم','اترك المهمة تكمل تلقائيًا بعد نجاح الربط'],requiredTools:['Alpaca Paper Trading API'],connectionRequest:req,confidence:1}}
const account=await call('/v2/account');
const evidence=[`Alpaca Paper account: ${account.id||'connected'}`,`Paper status: ${account.status||'unknown'}`,`Equity: ${account.equity||'unknown'}`,`Buying power: ${account.buying_power||'unknown'}`,`Retrieved: ${now()}`];
const side=explicitSide(text);
if(!side){const positions=await call('/v2/positions');return {status:'COMPLETE',summary:'تم ربط وقراءة محفظة Alpaca Paper بنجاح.',deliverable:`الرصيد الورقي: ${account.equity||'غير متاح'} USD\nالقوة الشرائية: ${account.buying_power||'غير متاحة'} USD\nعدد المراكز المفتوحة: ${Array.isArray(positions)?positions.length:0}`,evidence:[...evidence,`Open paper positions: ${Array.isArray(positions)?positions.length:0}`],nextActions:[],requiredTools:[],paperTrading:true,confidence:1}}
const symbol=symbolFrom(`${task.title||''} ${task.details||''}`.toUpperCase());if(!symbol)return {status:'NEEDS_APPROVAL',summary:'أحتاج رمز الأصل قبل إرسال أمر Paper. مثال: AAPL أو NVDA أو BTCUSD.',deliverable:'لم يتم إرسال أي أمر.',evidence,requiredTools:[],nextActions:['حدد رمز الأصل'],confidence:1};
const notional=amountFrom(text),qty=qtyFrom(text);if(!notional&&!qty)return {status:'NEEDS_APPROVAL',summary:`حدد حجم الأمر الورقي لـ ${symbol} (مثلاً 250 دولار أو 2 سهم).`,deliverable:'لم يتم إرسال أي أمر.',evidence,requiredTools:[],nextActions:['حدد حجم الصفقة'],confidence:1};
const orderBody={symbol,side,type:'market',time_in_force:'day'};if(notional)orderBody.notional=String(notional);else orderBody.qty=String(qty);
const order=await call('/v2/orders',{method:'POST',body:JSON.stringify(orderBody)});return {status:'COMPLETE',summary:`تم إرسال أمر ${side==='buy'?'شراء':'بيع'} ورقي حقيقي إلى Alpaca Paper.`,deliverable:`${symbol} • ${side} • ${notional?notional+' USD':qty+' shares'} • حالة الأمر: ${order.status||'accepted'}`,evidence:[...evidence,`Paper order id: ${order.id}`,`Client order id: ${order.client_order_id||'n/a'}`,`Order status: ${order.status||'unknown'}`],nextActions:['متابعة حالة الأمر والمركز'],requiredTools:[],paperTrading:true,order,confidence:1}}
