import { readFileSync } from "node:fs";
import { Script } from "node:vm";
const read = name => readFileSync(new URL(`../dist/${name}`, import.meta.url), "utf8");
const html=read('index.html');
const app=read('hq-shell-v8.js');
const css=read('hq-shell-v8.css');
const agent=read('hq-agent-runtime.js');
const executor=read('hq-project-executor.js');
const apps=read('hq-apps-page.js');
const cloud=read('hq-cloud-sync.js');
const icons=read('hq-icons-v10.js');
const iconsCss=read('hq-icons-v10.css');
const finance=read('hq-finance-v1.js');
const quality=read('hq-quality-v11.js');
const qualityCss=read('hq-quality-v11.css');
new Script(app);new Script(agent);new Script(executor);new Script(apps);new Script(cloud);new Script(icons);new Script(finance);new Script(quality);
for(const asset of ['hq-shell-v8.css','hq-shell-v8.js','hq-agent-runtime.js','hq-project-executor.js','hq-executive-secretary.js','hq-cloud-sync.js','hq-icons-v10.css','hq-icons-v10.js','hq-finance-v1.js','hq-quality-v11.css','hq-quality-v11.js'])if(!html.includes(asset))throw new Error(`Missing asset ${asset}`);
for(const view of ['dashboard','workforce','projects','tasks','reports'])if(!app.includes(`'${view}'`)&&!app.includes(`\"${view}\"`))throw new Error(`Missing view ${view}`);
for(const action of ['data-view','data-employee','data-project','data-task','data-report','new-employee','new-task','company-command'])if(!app.includes(action))throw new Error(`Missing interaction ${action}`);
for(const employee of ['سارة','عمر','ليان','نورة'])if(!app.includes(employee))throw new Error(`Missing employee ${employee}`);
for(const project of ['مُعِين','قدّها','ناڤ'])if(!app.includes(project))throw new Error(`Missing project ${project}`);
for(const link of ['mueen-islamic-app.vercel.app','qaddha.vercel.app','github.com/uauz1/mueen-islamic-app','github.com/uauz1/game'])if(!app.includes(link)&&!apps.includes(link))throw new Error(`Missing project link ${link}`);
for(const runtime of ['runTask','runNext','/api/worker'])if(!agent.includes(runtime))throw new Error(`Missing runtime ${runtime}`);
for(const runtime of ['/api/project-execute','NawafProjectExecutor','runTask','permissionBlock','projectAccess','permissions'])if(!executor.includes(runtime))throw new Error(`Missing project executor ${runtime}`);
for(const syncFeature of ['/api/state','baseUpdatedAt','r.status===409','mergeState','HQCloud'])if(!cloud.includes(syncFeature))throw new Error(`Missing cloud sync feature ${syncFeature}`);
for(const iconFeature of ['dashboard','workforce','projects','tasks','reports','userPlus','command','external','github','edit','bolt','sync','close','apps'])if(!icons.includes(`${iconFeature}:`)&&!icons.includes(`'${iconFeature}'`)&&!icons.includes(`\"${iconFeature}\"`))throw new Error(`Missing V10 icon ${iconFeature}`);
for(const financeFeature of ['finance','المحلل المالي والاستثماري','تحليل سهم','تقييم مالي','مراجعة محفظة','لا تنفذ أي شراء أو بيع'])if(!finance.includes(financeFeature))throw new Error(`Missing finance feature ${financeFeature}`);
for(const qualityFeature of ['/api/health','openPalette','v11-mobile-nav','unhandledrejection','preventDoubleSubmit','بحث سريع','المحلل المالي'])if(!quality.includes(qualityFeature)&&!qualityCss.includes(qualityFeature))throw new Error(`Missing V11 quality feature ${qualityFeature}`);
if(!css.trim()||!iconsCss.trim()||!qualityCss.trim())throw new Error('Production stylesheet empty');
console.log('Nawaf HQ V11 production quality + finance + cloud sync + permissions smoke checks passed');
