import { readFileSync } from "node:fs";
import { Script } from "node:vm";
const read = name => readFileSync(new URL(`../dist/${name}`, import.meta.url), "utf8");
const readRoot = name => readFileSync(new URL(`../${name}`, import.meta.url), "utf8");
const html=read('index.html');
const app=read('hq-shell-v8.js');
const css=read('hq-shell-v8.css');
const agent=read('hq-agent-runtime.js');
const executor=read('hq-project-executor.js');
const apps=read('hq-apps-page.js');
const cloud=read('hq-cloud-sync.js');
const icons=read('hq-icons-v10.js');
const iconsCss=read('hq-icons-v10.css');
const finance=read('hq-finance-v1.js');
const quality=read('hq-quality-v11.js');
const qualityCss=read('hq-quality-v11.css');
const ops=read('hq-ops-v12.js');
const opsCss=read('hq-ops-v12.css');
const ceo=read('hq-ceo-v13.js');
const ceoCss=read('hq-ceo-v13.css');
const dash=read('hq-dashboard-v14.js');
const dashCss=read('hq-dashboard-v14.css');
const companyOs=read('hq-company-os-v15.js');
const companyOsCss=read('hq-company-os-v15.css');
const companyOsV23=read('hq-company-os-v23.js');
const companyOsV23Css=read('hq-company-os-v23.css');
const server=readRoot('render-server-v2.mjs');
const stateCloud=readRoot('state-cloud.mjs');
new Script(app);new Script(agent);new Script(executor);new Script(apps);new Script(cloud);new Script(icons);new Script(finance);new Script(quality);new Script(ops);new Script(ceo);new Script(dash);new Script(companyOs);new Script(companyOsV23);
for(const asset of ['hq-shell-v8.css','hq-shell-v8.js','hq-agent-runtime.js','hq-project-executor.js','hq-executive-secretary.js','hq-cloud-sync.js','hq-finance-v1.js','hq-smart-command.js','hq-secretary-truth.js','hq-truthful-task-ui-v17.js'])if(!html.includes(asset))throw new Error(`Missing asset ${asset}`);
for(const view of ['dashboard','workforce','projects','tasks','reports'])if(!app.includes(`'${view}'`)&&!app.includes(`\"${view}\"`))throw new Error(`Missing view ${view}`);
for(const action of ['data-view','data-employee','data-project','data-task','data-report','new-employee','new-task','company-command'])if(!app.includes(action))throw new Error(`Missing interaction ${action}`);
for(const binding of ["document.addEventListener('click'","closest('[data-view]')","closest('[data-action]')","closest('[data-employee]')","closest('[data-project]')","closest('[data-task]')","closest('[data-report]')","closest('[data-run-task]')","closest('[data-project-task]')","employeeModal(emp.dataset.employee)","projectModal(p.dataset.project)","taskModal(t.dataset.task)","reportModal(r.dataset.report)","runTask(run.dataset.runTask)","$('#v8-command-form').onsubmit","$('#v8-employee-form').onsubmit"])if(!app.includes(binding))throw new Error(`Missing click/form wiring ${binding}`);
for(const employee of ['سارة','عمر','ليان','نورة'])if(!app.includes(employee))throw new Error(`Missing employee ${employee}`);
for(const project of ['مُعِين','قدّها','ناڤ'])if(!app.includes(project))throw new Error(`Missing project ${project}`);
for(const link of ['mueen-islamic-app.vercel.app','qaddha.vercel.app','github.com/uauz1/mueen-islamic-app','github.com/uauz1/game'])if(!app.includes(link)&&!apps.includes(link))throw new Error(`Missing project link ${link}`);
for(const runtime of ['async function runTask','async function runNext','/api/worker','invokeWorker','window.NawafAgents'])if(!agent.includes(runtime))throw new Error(`Missing verified agent runtime ${runtime}`);
if(agent.includes('if(!s.companyStarted)')||agent.includes('ابدأ الشركة أولاً ثم شغّل الموظفين'))throw new Error('Hidden company-start gate still blocks direct execution');
for(const runtime of ['NawafProjectExecutor','runTask','legacy:false','NawafAgents'])if(!executor.includes(runtime))throw new Error(`Missing unified project executor compatibility ${runtime}`);
for(const syncFeature of ['/api/state','baseUpdatedAt','r.status===409','mergeState','HQCloud'])if(!cloud.includes(syncFeature))throw new Error(`Missing cloud sync feature ${syncFeature}`);
for(const serverFeature of ['loadCloudState','saveCloudState','backgroundTick','executeRealProjectTask','VERIFIED_EVIDENCE','backgroundWorker:true'])if(!server.includes(serverFeature))throw new Error(`Missing real server worker feature ${serverFeature}`);
for(const cloudFeature of ['export async function loadCloudState','export async function saveCloudState','STATE_CONFLICT'])if(!stateCloud.includes(cloudFeature))throw new Error(`Missing server cloud state feature ${cloudFeature}`);
if(server.includes('task.progress=Math.max(10')||server.includes('task.progress=Math.max(20')||agent.includes('t.progress=10')||executor.includes('progress=Math.max(12')||executor.includes('progress=Math.max(55'))throw new Error('Fake progress logic remains in worker runtime');
for(const iconFeature of ['dashboard','workforce','projects','tasks','reports','userPlus','command','external','github','edit','bolt','sync','close','apps'])if(!icons.includes(`${iconFeature}:`)&&!icons.includes(`'${iconFeature}'`)&&!icons.includes(`\"${iconFeature}\"`))throw new Error(`Missing V10 icon ${iconFeature}`);
for(const financeFeature of ['finance','المحلل المالي ونمو الأعمال','نمو وربحية مشروع','تحليل سهم','تقييم مالي','مراجعة محفظة','لا تنفذ أي شراء أو بيع أو تحويل أو صرف أموال'])if(!finance.includes(financeFeature))throw new Error(`Missing finance feature ${financeFeature}`);
for(const qualityFeature of ['/api/health','openPalette','v11-mobile-nav','unhandledrejection','preventDoubleSubmit','بحث سريع','المحلل المالي'])if(!quality.includes(qualityFeature)&&!qualityCss.includes(qualityFeature))throw new Error(`Missing V11 quality feature ${qualityFeature}`);
for(const opsFeature of ['openNotifications','openActivity','openRecovery','retryTask','v12-dock','استعادة المهام','منهج راكان'])if(!ops.includes(opsFeature)&&!opsCss.includes(opsFeature))throw new Error(`Missing V12 ops feature ${opsFeature}`);
for(const ceoFeature of ['openCenter','approve','reject','reopen','ceoBrief','مركز قرارات نواف','موافقة وإكمال','رفض وإغلاق','v13-center'])if(!ceo.includes(ceoFeature)&&!ceoCss.includes(ceoFeature))throw new Error(`Missing V13 CEO feature ${ceoFeature}`);
for(const dashFeature of ['stateStats','projectHealth','employeeLoad','priority','أولوياتك الآن','حالة المشاريع','الفريق','CONNECTED TOOLS','الأدوات المربوطة','QUICK ACTIONS','v14-dashboard'])if(!dash.includes(dashFeature)&&!dashCss.includes(dashFeature))throw new Error(`Missing V14 dashboard feature ${dashFeature}`);
for(const osFeature of ['managerRun','runCompanyGoal','qaSweep','researchCenter','meetingRoom','projectMemory','permissions','deployments','costCenter','morning','شغّل الشركة','Inbox القرارات','Morning Brief','مركز الجودة QA','غرفة اجتماعات AI','ذاكرة المشاريع'])if(!companyOs.includes(osFeature)&&!companyOsCss.includes(osFeature))throw new Error(`Missing V15 company OS feature ${osFeature}`);
if(!dash.includes('NawafHQV13?.openCenter?.()'))throw new Error('V14 decisions action is not wired to V13 openCenter');
if(dash.includes('openDecisions'))throw new Error('Deprecated V14 decisions action remains');
if(!dash.includes('NawafHQV12?.openActivity?.()'))throw new Error('V14 activity action is not wired to V12');
if(!dash.includes('NawafFinance?.open?.()'))throw new Error('V14 finance action is not wired');
if(!dash.includes('HQCloud?.pull?.()'))throw new Error('V14 sync action is not wired');
for(const f of ['integrations','QA Gate','timeline','recovery','NawafHQV23'])if(!companyOsV23.includes(f))throw new Error(`Missing V23 feature ${f}`);
for(const financeFeature of ['watchlist','finance-watchlist','قائمة المراقبة','تحليل مع راكان'])if(!finance.includes(financeFeature))throw new Error(`Missing finance watchlist feature ${financeFeature}`);
if(!cloud.includes('finance')||!cloud.includes('watchlist'))throw new Error('Finance watchlist is not included in client cloud sync');
if(!stateCloud.includes('finance')||!stateCloud.includes('watchlist'))throw new Error('Finance watchlist is not included in server cloud merge');
if(!companyOsV23Css.trim())throw new Error('V23 stylesheet empty');
if(!html.includes('hq-company-os-v23.js')||!html.includes('hq-company-os-v23.css'))throw new Error('V23 assets not activated');
if(!css.trim()||!iconsCss.trim()||!qualityCss.trim()||!opsCss.trim()||!ceoCss.trim()||!dashCss.trim()||!companyOsCss.trim())throw new Error('Production stylesheet empty');
console.log('Nawaf HQ verified worker + background execution + simplified dashboard + decisions + operations + quality + finance + cloud sync checks passed');

if(!server.includes('QA_GATE_FAILED'))throw new Error('server must expose explicit QA gate failure');
if(!server.includes("qaFailed?'QA_GATE':'MISSING_TOOL'"))throw new Error('QA failure must not be mislabeled as missing tool');
