import { readFileSync } from "node:fs";
import { Script } from "node:vm";
const read = name => readFileSync(new URL(`../dist/${name}`, import.meta.url), "utf8");
const html=read('index.html');
const app=read('hq-shell-v8.js');
const css=read('hq-shell-v8.css');
const agent=read('hq-agent-runtime.js');
const executor=read('hq-project-executor.js');
const apps=read('hq-apps-page.js');
new Script(app);new Script(agent);new Script(executor);new Script(apps);
for(const asset of ['hq-shell-v8.css','hq-shell-v8.js','hq-agent-runtime.js','hq-project-executor.js','hq-executive-secretary.js'])if(!html.includes(asset))throw new Error(`Missing asset ${asset}`);
for(const view of ['dashboard','workforce','projects','tasks','reports'])if(!app.includes(`'${view}'`)&&!app.includes(`\"${view}\"`))throw new Error(`Missing view ${view}`);
for(const action of ['data-view','data-employee','data-project','data-task','data-report','new-employee','new-task','company-command'])if(!app.includes(action))throw new Error(`Missing interaction ${action}`);
for(const employee of ['سارة','عمر','ليان','نورة'])if(!app.includes(employee))throw new Error(`Missing employee ${employee}`);
for(const project of ['مُعِين','قدّها','ناڤ'])if(!app.includes(project))throw new Error(`Missing project ${project}`);
for(const link of ['mueen-islamic-app.vercel.app','qaddha.vercel.app','github.com/uauz1/mueen-islamic-app','github.com/uauz1/game'])if(!app.includes(link)&&!apps.includes(link))throw new Error(`Missing project link ${link}`);
for(const runtime of ['runTask','runNext','/api/worker'])if(!agent.includes(runtime))throw new Error(`Missing runtime ${runtime}`);
for(const runtime of ['/api/project-execute','NawafProjectExecutor','runTask'])if(!executor.includes(runtime))throw new Error(`Missing project executor ${runtime}`);
if(!css.trim())throw new Error('V8 stylesheet empty');
console.log('Nawaf HQ V8 smoke checks passed');
