export const transitions = {
  QUEUED: ['ROUTING','CANCELLED'], ROUTING: ['PLANNING','WAITING_FOR_CONNECTION','WAITING_FOR_APPROVAL','BLOCKED','FAILED'],
  PLANNING: ['WORKING','RESEARCHING','REVIEWING','WAITING_FOR_CONNECTION','WAITING_FOR_APPROVAL','FAILED'],
  WORKING: ['REVIEWING','PAUSED_EXTERNAL','WAITING_FOR_CONNECTION','WAITING_FOR_APPROVAL','COMPLETED','FAILED','CANCELLED'],
  RESEARCHING: ['REVIEWING','PAUSED_EXTERNAL','WAITING_FOR_CONNECTION','COMPLETED','FAILED','CANCELLED'],
  REVIEWING: ['COMPLETED','BLOCKED','PAUSED_EXTERNAL','FAILED','CANCELLED'], WAITING_FOR_CONNECTION: ['QUEUED','CANCELLED'],
  WAITING_FOR_APPROVAL: ['QUEUED','CANCELLED'], PAUSED_EXTERNAL: ['QUEUED','FAILED','CANCELLED'],
  BLOCKED: ['QUEUED','CANCELLED'], FAILED: ['QUEUED','CANCELLED'], COMPLETED: [], CANCELLED: []
};

export function assertTransition(from, to) {
  if (!transitions[from]?.includes(to)) throw new Error(`INVALID_TASK_TRANSITION:${from}->${to}`);
  return true;
}

export const activeStatuses = new Set(['ROUTING','PLANNING','WORKING','RESEARCHING','REVIEWING']);
